Section 3.1 - цикл while
aleno4ka1998/gentle_lerning pull request #3
Opened 2020-11-17 21:41 UTC by aleno4ka1998

Мне кажется лучше поделить задачи 3 секции на задачи по for и while, а то их довольно много и там и там

2020-11-18 01:54 UTC, thelightningseas approved these changes

2020-11-22 17:06 UTC, thelightningseas requested changes

2020-11-22 17:06 UTC, thelightningseas commented on section3_1/average sequence_number.py
> +    if a != 0:
а можно было бы тут обойтись без двух проверок, что a не равен 0?

2020-11-22 17:06 UTC, thelightningseas commented on section3_1/bank_interest.py
> +while x < y:
а понятно как сделать без цикла такую задачу? в одну строчку

2020-11-22 17:06 UTC, thelightningseas commented on section3_1/fibonacci.py
> +while k != n:
кажется, конструкция ```while k != n: k += 1``` эквивалентна ```for _ in range(n)```, но выглядит более громоздко

2020-11-22 17:06 UTC, thelightningseas commented on section3_1/max_of_sequence.py
> +    k = a
а зачем тут ```k```?

2020-11-22 17:06 UTC, thelightningseas commented on section3_1/sequence_length.py
> +while n != 0:
опять очень перегруженно

```
sequence_length = 0
while True:
    next_num = int(input())
    if next_num == 0:
        break
    sequence_length += 1
print(sequence_length)
```

2020-11-22 18:16 UTC, aleno4ka1998 commented on section3_1/average sequence_number.py
> +    if a != 0:
да, можно объявить первый инпут перед циклом, а в самом цикле поменять местами расчёты и инпут

2020-11-22 19:18 UTC, aleno4ka1998 commented on section3_1/bank_interest.py
> +while x < y:
Можно
x = int(input())
p = int(input())
y = int(input())
k = round(y / (int(x + x / 100 * p)))
print(k)

2020-11-22 19:31 UTC, aleno4ka1998 commented on section3_1/fibonacci.py
> +while k != n:
все время кажется что если задача в рамках раздела "Задачи на цикл while", то нужно использовать цикл while)

2020-11-22 19:57 UTC, aleno4ka1998 commented on section3_1/max_of_sequence.py
> +    k = a
Прошу прощения, прога нерабочая. Вот, исправляюсь:
a = int(input())
maximum = 0
while a != 0:
    if a > maximum:
        maximum = a
    a = int(input())
print(maximum)

2020-11-22 20:36 UTC, aleno4ka1998 commented on section3_1/sequence_length.py
> +while n != 0:
while True продолжает цикл до события вызывающего break?

2020-11-24 11:16 UTC, thelightningseas requested changes

2020-11-24 11:16 UTC, thelightningseas commented on section3_1/quantity of maximum numbers.py
> +maximum = 0
ну тут решение не верное)

2020-11-24 11:16 UTC, thelightningseas commented on section3_1/sequence_sum_2.py
> +a = 0
очень запутано. лучше что то такое:
```
sequence_sum = 0
last_number_is_zero = False

while True:
    next_number = int(input())
    if next_number == 0 and last_number_is_zero:
        break
    elif next_number == 0:
        last_number_is_zero = True
    else:
        sequence_sum += next_number
        last_number_is_zero = False

print(sequence_sum)
```

2020-11-26 21:41 UTC, aleno4ka1998 commented on section3_1/quantity of maximum numbers.py
> +maximum = 0
Почему? Сначала находим первый элемент-максимум, потом равные ему

2020-11-26 22:01 UTC, thelightningseas approved these changes

2020-11-29 11:31 UTC, thelightningseas approved these changes

2020-11-29 19:10 UTC, thelightningseas commented on section3_1/sequence_length.py
> +while n != 0:
да. или до бесконечности если его не будет)

вообще ```while condition``` работает как раз так ведь
смотрит на ```condition``` которы там написан (например ```n != 0```) если то что в нем написано - ```True```, делает еще итерацию, если ```False``` - останавливается. вайл тру просто всегда верен

2020-11-30 08:39 UTC, thelightningseas commented on section3_1/minimum and maximum.py
> +    max_d = 0
```max_d``` не очень хорошо. лучше писать целиком ```max_digit```. Но в нашем случае, когда из названия функции понятно, что она вернет, можно назвать например ```result``` и будет хорошо

2020-11-30 08:40 UTC, thelightningseas commented on section3_1/minimum and maximum.py
> +    max_d = 0
и если пишешь тайп хинтинги, то лучше возвращаемое значение тоже указывать
```
def max_digit(n: int) -> int:
   #  some code here
```

2020-11-30 08:41 UTC, thelightningseas commented on section3_1/number of polyindromes.py
> +    rev = str('')
слишком сложная инициализация строки)
лучше или просто ```rev = str()``` или ```rev = ''```

2020-11-30 08:41 UTC, thelightningseas approved these changes

2020-11-30 23:01 UTC, merged