Section 4.3
aleno4ka1998/gentle_lerning pull request #6
Opened 2020-12-19 23:01 UTC by aleno4ka1998

Классы

2020-12-19 23:02 UTC, aleno4ka1998 reviewed
здесь я затупила немножечко

2020-12-20 21:45 UTC, thelightningseas requested changes

2020-12-20 21:45 UTC, thelightningseas commented on section4.3/average score in subjects.py
> +        self.a = surname
с такими названиями совершенно непонятно что это за поля. с таким интерфейсом проще использовать список вместо класса)

2020-12-20 21:45 UTC, thelightningseas commented on section4.3/average score in subjects.py
> +        self.a = surname
возможно если бы сущностью (классом) в этой задаче был не школьник а предмет, было бы проще и понеятнее

2020-12-20 21:45 UTC, thelightningseas commented on section4.3/maximum area.py
> +class SetOfCoordinates:
если вместо метода который просто аппендит, сделать метод, который сразу обновляет значение максимума, было бы понятнее

человеку, используюещему класс хочется как раз этого - все действия происходят где-то под капотом, а он только использует понятный интерфейс

2020-12-23 22:34 UTC, thelightningseas requested changes

2020-12-23 22:34 UTC, thelightningseas commented on section4.3/best students.py
> +        self.a = surname
с такими названиями полей никто кроме тебя не сможет пользоваться этим кассом

2020-12-23 22:53 UTC, aleno4ka1998 commented on section4.3/best students.py
> +        self.a = surname
Ты про a, b, c и т.д. в ините?

2020-12-23 22:54 UTC, thelightningseas commented on section4.3/best students.py
> +        self.a = surname
Да

2020-12-23 22:54 UTC, thelightningseas commented on section4.3/best students.py
> +        self.a = surname
![image](https://user-images.githubusercontent.com/46321152/103042535-04e7c180-458b-11eb-93a5-aa02c87869e1.jpeg)

2020-12-24 09:28 UTC, thelightningseas approved these changes

2020-12-24 09:28 UTC, thelightningseas commented on section4.3/best students.py
> +print('\n'.join(map(str, B)))
мне кажется, понятнее было бы 
```
for pupil in B:
    print(pupil)
```

2020-12-25 22:06 UTC, thelightningseas approved these changes

2020-12-31 11:07 UTC, thelightningseas approved these changes

2020-12-31 11:07 UTC, thelightningseas commented on section4.3/personal documents.py
> +    surname = str(input())
не надо делать str(input()), input() и так возрващает строку, так приходилось делать когда из этой строки хотелось получить число

2020-12-31 15:22 UTC, merged